# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: serverless CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: cnpm install
    - name: Install serverless
      run: cnpm install -g serverless 
    - name: Auto deploy   
      env: # Or as an environment variable
        STAGE: prod
        SERVERLESS_PLATFORM_VENDOR: tencent
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}     
      run: 
        sls deploy --debug
